### ISSUE TITLE
Package not Found

### ISSUE THREAD

**Issue by jdgabriel** [getomni/insomnia#6]
Package @getomni/insomnia not found in insominia plugins.
I tried to search for "getomni/insomnia", but I didn't find it either.

**Expected behavior**
Package not found

**Screenshots**
none

**Environment:**
none

**Additional context**
none

**Comment by jpedroschmitz** [comment]
Hey, I have done the installation process again and it's going pretty well - [video link](https://vimeo.com/472595429).

Also, the package was published on `npm`, and you can [check it here](https://www.npmjs.com/package/@getomni/insomnia).


I will be closing this since the package is found and installed correctly. 
In case others have the same problem, I can reopen the issue.

**Comment by akinncar** [comment]
Hey, I have found the same issue

![image](https://user-images.githubusercontent.com/42688281/108388249-324c9680-71ed-11eb-838b-c2d643f6715c.png)

**Comment by jpedroschmitz** [comment]
Hey @akinncar, could you please send a picture with the full error message? 
Just click on the `Additional Information` and send it here.

**Comment by akinncar** [comment]
This is the error message

![print-omni](https://user-images.githubusercontent.com/42688281/108420755-fb897700-7212-11eb-8473-7e3a7b8d1247.png)

Now I'm not sure if it is an error for getomni package, by the way, I found a temporary solution [here](https://github.com/Kong/insomnia/issues/905#issuecomment-519472520)

1- `cd /home/user/snap/insomnia/current/.config/Insomnia/plugins
`
2- `yarn add @getomni/insomnia`
